# Generated by Django 5.2.11 on 2026-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('BLOCKED', 'Bloqué'), ('DONE', 'Terminé')], default='TODO', max_length=20),
        ),
    ]
