# Generated by Django 6.0.2 on 2026-03-13 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectstep'),
        ('trainings', '0030_trainer_is_active_trainer_workload_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'order', 'id'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Charge estimée globale (jours)'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('todo', 'À lancer'), ('doing', 'En cours'), ('blocked', 'Bloqué'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date cible'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Charge estimée (jours)'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue de début'),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Charge planifiée (jours)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('status', models.CharField(choices=[('forecast', 'Prévisionnel'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='forecast', max_length=20)),
                ('is_visible_in_one_to_one', models.BooleanField(default=True, verbose_name='Visible dans les 1 to 1')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.task')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='trainings.trainer')),
            ],
            options={
                'verbose_name': 'Affectation de tâche',
                'verbose_name_plural': 'Affectations de tâches',
                'ordering': ['start_date', 'end_date', 'task__project__name', 'task__title'],
                'unique_together': {('task', 'trainer', 'start_date', 'end_date')},
            },
        ),
    ]
