# Generated by Django 5.2.11 on 2026-02-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0021_mercurecontract_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceMercureContract',
            fields=[
            ],
            options={
                'verbose_name': 'Contrat d’application',
                'verbose_name_plural': 'Contrats d’application',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.mercurecontract',),
        ),
        migrations.CreateModel(
            name='FinanceMercureInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.mercureinvoice',),
        ),
    ]
