# Generated by Django 5.2.11 on 2026-02-20 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0016_trainer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgonosTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('TECH', 'Technique'), ('FUNC', 'Fonctionnelle')], default='TECH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ArgonosModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('TECH', 'Technique'), ('FUNC', 'Fonctionnelle')], default='TECH', max_length=10)),
                ('level', models.CharField(choices=[('L1', 'Niveau 1'), ('L2', 'Niveau 2'), ('L3', 'Niveau 3')], default='L1', max_length=10)),
                ('major_version', models.PositiveIntegerField(default=1)),
                ('current_patch', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='argonteam.argonosmodule')),
            ],
            options={
                'ordering': ('kind', 'level', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OneToOneMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='Semaine du (lundi)')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Date du 1 to 1')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé')], default='DRAFT', max_length=20)),
                ('summary', models.TextField(blank=True, default='', verbose_name='Résumé (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_ones', to='trainings.trainer')),
            ],
            options={
                'ordering': ('-week_start',),
                'unique_together': {('trainer', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='OneToOneObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRAINING', 'Formations réalisées'), ('GOAL', 'Objectifs'), ('OTHER', 'Autres points')], default='GOAL', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Objectif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('BLOCKED', 'Bloqué'), ('DONE', 'Terminé')], default='TODO', max_length=20)),
                ('actionable', models.BooleanField(default=False, verbose_name='Créer une tâche Kanban')),
                ('created_task_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='argonteam.argonosmodule', verbose_name='Module lié (optionnel)')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='argonteam.onetoonemeeting')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_objectives', to='trainings.trainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArgonosTrackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_steps', to='argonteam.argonosmodule')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='argonteam.argonostrack')),
            ],
            options={
                'ordering': ('track', 'order'),
                'unique_together': {('track', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TrainerModuleMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_level', models.CharField(choices=[('L1', 'Auto L1'), ('L2', 'Auto L2'), ('L3', 'Auto L3')], default='L1', max_length=10)),
                ('manager_status', models.CharField(choices=[('PENDING', 'En attente'), ('OK', 'OK'), ('KO', 'KO')], default='PENDING', max_length=10)),
                ('cert_status', models.CharField(choices=[('PENDING', 'En attente'), ('OK', 'OK'), ('KO', 'KO')], default='PENDING', max_length=10)),
                ('validated_major', models.PositiveIntegerField(blank=True, null=True)),
                ('validated_patch', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_masteries', to='argonteam.argonosmodule')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_masteries', to='trainings.trainer')),
            ],
            options={
                'ordering': ('trainer__last_name', 'module__kind', 'module__name'),
                'unique_together': {('trainer', 'module')},
            },
        ),
        migrations.CreateModel(
            name='TrainerTrackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_level', models.CharField(choices=[('L1', 'Niveau 1'), ('L2', 'Niveau 2'), ('L3', 'Niveau 3')], default='L1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_progress', to='argonteam.argonostrack')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_progress', to='trainings.trainer')),
            ],
            options={
                'ordering': ('trainer__last_name', 'track__kind', 'track__name'),
                'unique_together': {('trainer', 'track')},
            },
        ),
    ]
