# Generated by Django 5.2.11 on 2026-02-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_referrer_participant_company_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrers', to='trainings.client'),
        ),
    ]
