# Generated by Django 5.2.11 on 2026-02-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_referrer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='trainings.client'),
        ),
    ]
