# Generated by Django 5.2.11 on 2026-02-14 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_participant_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='backup_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_sessions', to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='training_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='trainings.trainingtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_sessions', to='trainings.trainer'),
        ),
    ]
