# Generated by Django 5.2.11 on 2026-02-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_session_backup_trainer_session_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='session',
            name='on_client_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainings.room'),
        ),
    ]
