# Generated by Django 5.2.11 on 2026-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_session_client_address_session_on_client_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
