# Generated by Django 5.2.11 on 2026-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_training_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='accounting_sheets_sent_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi feuilles compta"),
        ),
        migrations.AddField(
            model_name='session',
            name='convocations_sent_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi des convocations"),
        ),
        migrations.AddField(
            model_name='session',
            name='report_sent_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi du bilan"),
        ),
        migrations.AddField(
            model_name='session',
            name='software_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Version du logiciel'),
        ),
    ]
