# Generated by Django 5.2.11 on 2026-02-15 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_session_accounting_sheets_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Satisfaction client (/20)'),
        ),
        migrations.AddField(
            model_name='session',
            name='participants_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de participants'),
        ),
    ]
