# Generated by Django 5.2.11 on 2026-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_session_client_satisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='participants_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Nombre de participants'),
        ),
    ]
