# Generated by Django 5.2.11 on 2026-02-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_alter_session_participants_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participants_count',
        ),
        migrations.AddField(
            model_name='session',
            name='expected_participants',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Nombre de participants prévu'),
        ),
        migrations.AddField(
            model_name='session',
            name='present_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Nombre de présents'),
        ),
    ]
