# Generated by Django 5.2.11 on 2026-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_remove_session_participants_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='work_environment',
            field=models.CharField(choices=[('PSFormation', 'PSFormation'), ('PSFormationMid', 'PSFormationMid')], default='PSFormation', max_length=20, verbose_name='Environnement de travail'),
        ),
    ]
