# Generated by Django 5.2.11 on 2026-02-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_session_work_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='convocation_alert_closed',
            field=models.BooleanField(default=False, verbose_name='Alerte convocation fermée'),
        ),
    ]
