# Generated by Django 5.2.11 on 2026-02-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_session_convocation_alert_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='trainings.participant'),
        ),
    ]
