# Generated by Django 5.2.11 on 2026-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_alter_registration_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants_invited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invitations participants envoyées le'),
        ),
        migrations.AddField(
            model_name='session',
            name='teams_meeting_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien Teams'),
        ),
    ]
