# Generated by Django 5.2.11 on 2026-02-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_session_participants_invited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='product',
            field=models.CharField(choices=[('MERCURE', 'Mercure'), ('ARGONOS', 'ArgonOS')], default='ARGONOS', max_length=20, verbose_name='Produit'),
        ),
    ]
