# Generated by Django 5.2.11 on 2026-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_trainer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='platform',
            field=models.CharField(choices=[('ARGONOS', 'ArgonOS'), ('MERCURE', 'Mercure')], default='ARGONOS', max_length=16),
        ),
    ]
