# Generated by Django 5.2.11 on 2026-02-26 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_trainer_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix formation HT'),
        ),
    ]
