# Generated by Django 5.2.11 on 2026-02-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_session_price_ht'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercureApplicationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('TO_SEND', 'À envoyer'), ('SENT', 'Envoyé'), ('SIGNED', 'Signé'), ('CANCELLED', 'Annulé')], default='TO_SEND', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercure_contract', to='trainings.session')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercure_contracts', to='trainings.trainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MercureInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=80)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('RECEIVED_ADMIN', 'Reçue (Service admin)'), ('WAITING_PROCESS', 'En attente de traitement'), ('PROCESSING', 'En cours de traitement'), ('VALIDATION', 'En cours de validation'), ('PAID', 'Payée')], default='RECEIVED_ADMIN', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions', models.ManyToManyField(blank=True, related_name='mercure_invoices', to='trainings.session')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercure_invoices', to='trainings.trainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
