# Generated by Django 5.2.11 on 2026-02-27 18:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_mercureapplicationcontract_mercureinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercureinvoice',
            name='invoice_ref',
        ),
        migrations.RemoveField(
            model_name='mercureinvoice',
            name='sessions',
        ),
        migrations.AddField(
            model_name='mercureinvoice',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mercureinvoice',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='mercure_invoices', to='trainings.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercureinvoice',
            name='amount_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='MercureContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TODO', 'À envoyer'), ('SENT', 'Envoyé'), ('SIGNED', 'Signé'), ('CANCELLED', 'Annulé')], default='TODO', max_length=20)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercure_contract', to='trainings.session')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercure_contracts', to='trainings.trainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='MercureApplicationContract',
        ),
    ]
