# Generated by Django 5.2.11 on 2026-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_remove_mercureinvoice_invoice_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercurecontract',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Référence'),
        ),
    ]
