# Generated by Django 5.2.11 on 2026-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0021_mercurecontract_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercureinvoice',
            name='document_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien facture'),
        ),
    ]
