# Generated by Django 5.2.11 on 2026-02-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_mercureinvoice_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercureinvoice',
            name='document_url',
        ),
        migrations.AddField(
            model_name='mercureinvoice',
            name='document_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Chemin facture (interne)'),
        ),
    ]
