# Generated by Django 5.2.11 on 2026-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_remove_mercureinvoice_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercureinvoice',
            name='payment_alert_closed',
            field=models.BooleanField(default=False, verbose_name='Alerte paiement fermée'),
        ),
    ]
