# Generated by Django 5.2.11 on 2026-03-04 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_mercureinvoice_payment_alert_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='client_satisfaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Satisfaction client (/20)'),
        ),
    ]
