# Generated by Django 5.2.11 on 2026-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0025_alter_session_client_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='service_address',
            field=models.TextField(blank=True, verbose_name='Adresse du service'),
        ),
    ]
