# Generated by Django 5.2.11 on 2026-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0026_referrer_service_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
