# Generated by Django 5.2.11 on 2026-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0027_alter_session_end_date_alter_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Partenaire'),
        ),
    ]
