# Generated by Django 6.0.2 on 2026-03-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0028_client_country_client_is_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerContractPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('price_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partner contract plan',
                'verbose_name_plural': 'Partner contract plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('draft', 'Draft')], default='active', max_length=20)),
                ('price_ht_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='trainings.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_contracts', to='trainings.partnercontractplan')),
            ],
            options={
                'verbose_name': 'Partner contract',
                'verbose_name_plural': 'Partner contracts',
                'ordering': ['-start_date', 'partner__name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerContractPlanSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_seats', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_rules', to='trainings.partnercontractplan')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contract_rules', to='trainings.training')),
            ],
            options={
                'verbose_name': 'Partner contract plan seat',
                'verbose_name_plural': 'Partner contract plan seats',
                'ordering': ['plan', 'training__title'],
                'unique_together': {('plan', 'training')},
            },
        ),
    ]
