# Generated by Django 6.0.2 on 2026-03-13 19:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0029_partnercontractplan_partnercontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='workload_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Capacité disponible (%)'),
        ),
        migrations.CreateModel(
            name='TrainerAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('VACATION', 'Congés'), ('RTT', 'RTT'), ('SICK', 'Maladie'), ('UNAVAILABLE', 'Indisponible'), ('INTERNAL', 'Réservé interne')], default='VACATION', max_length=20, verbose_name="Type d'absence")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('days_count', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Nombre de jours')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='trainings.trainer')),
            ],
            options={
                'verbose_name': 'Absence formateur',
                'verbose_name_plural': 'Absences formateurs',
                'ordering': ('start_date', 'trainer__last_name', 'trainer__first_name'),
            },
        ),
        migrations.CreateModel(
            name='TrainerWorkloadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_type', models.CharField(choices=[('PREPARATION', 'Préparation'), ('PROJECT', 'Projet transverse'), ('QA', 'QA / Documentation'), ('MEETING', 'Réunion'), ('SUPPORT', 'Support'), ('TRAVEL', 'Déplacement'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de charge')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('days_count', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Nombre de jours')),
                ('status', models.CharField(choices=[('FORECAST', 'Prévisionnel'), ('CONFIRMED', 'Confirmé'), ('DONE', 'Réalisé'), ('CANCELED', 'Annulé')], default='FORECAST', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_entries', to='trainings.trainer')),
            ],
            options={
                'verbose_name': 'Charge formateur',
                'verbose_name_plural': 'Charges formateurs',
                'ordering': ('start_date', 'trainer__last_name', 'trainer__first_name'),
            },
        ),
    ]
