# Generated by Django 6.0.2 on 2026-03-14 11:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0030_trainer_is_active_trainer_workload_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='applied_unit_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif participant appliqué HT'),
        ),
        migrations.AddField(
            model_name='registration',
            name='billed_amount_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant facturable HT'),
        ),
        migrations.AddField(
            model_name='registration',
            name='billing_rate_percent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Annulation 0%'), (30, 'Annulation 30%'), (100, 'Facturation 100%')], default=100, verbose_name='Taux de facturation (%)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='canceled_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Place offerte'),
        ),
        migrations.AddField(
            model_name='session',
            name='applied_participant_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif participant par défaut appliqué HT'),
        ),
        migrations.AddField(
            model_name='session',
            name='applied_session_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif session appliqué HT'),
        ),
        migrations.AddField(
            model_name='session',
            name='billing_mode',
            field=models.CharField(choices=[('COLLECTIVE', 'Inscription collective'), ('INDIVIDUAL', 'Inscriptions individuelles')], default='COLLECTIVE', max_length=20, verbose_name="Mode d'inscription"),
        ),
        migrations.AddField(
            model_name='session',
            name='is_abroad',
            field=models.BooleanField(default=False, verbose_name="Formation à l'étranger"),
        ),
        migrations.AddField(
            model_name='session',
            name='training_price_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix formation HT'),
        ),
        migrations.AddField(
            model_name='session',
            name='travel_fee_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais de déplacement HT'),
        ),
        migrations.AddField(
            model_name='training',
            name='participant_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif participant HT'),
        ),
        migrations.AddField(
            model_name='training',
            name='partner_participant_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif participant partenaire HT'),
        ),
        migrations.AddField(
            model_name='training',
            name='partner_session_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif session partenaire HT'),
        ),
        migrations.AddField(
            model_name='training',
            name='session_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif session HT'),
        ),
        migrations.AlterField(
            model_name='session',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix total HT'),
        ),
    ]
